Repository Whats-Cookin/trust_claim_backend, pull requests merged in 2025-03, with the labels that each got.

#199 doc(cred): add the endpoint to adding the creds as claim
  docs/swagger/swagger.yaml
Labels: documentation

#200 refactor(graph): implement getGraphNode function to retrieve claim gr…
  src/controllers/api.controller.ts
  src/controllers/index.ts
  src/dao/api.dao.ts
  src/dao/graph.ts
  src/routes/apiRoutes/api.route.ts
Labels: enhancement

#201 feat(graph): add host parameter to getClaimGraph and expandGraph func…
  src/controllers/api.controller.ts
  src/dao/api.dao.ts
  src/dao/graph.ts
Labels: bug

#202 refactor(graph): restructure GraphNode and GraphEdge interfaces to us…
  src/dao/graph.ts
  src/utils/index.ts
Labels: enhancement

#203 fix(graph): remove BASE_URL dependency in getGraphNode function for c…
  src/dao/graph.ts
Labels: bug

#204 Feat/create mapping for credential auther
  src/controllers/api.controller.ts
  src/middlewares/validators/claim.validator.ts
Labels: enhancement

#206 fix(api): add author field to createClaim function
  src/dao/api.dao.ts
Labels: bug

#205 feat(claim): add author & curator fields with username extraction fro…
  src/dao/api.dao.ts
  src/utils/index.ts
Labels: enhancement

#207 feat(graph): enhance expandGraph function to support multiple graph t…
  src/controllers/api.controller.ts
  src/dao/api.dao.ts
  src/dao/graph.ts
  src/types/utils.ts
Labels: enhancement

#215 fix: update author and curator fields in credential and claim handling
  src/controllers/api.controller.ts
  src/dao/api.dao.ts
  src/dao/graph.ts
  src/middlewares/validators/claim.validator.ts
Labels: enhancement

#217 fix: update relation and source/target mapping in graph node retrieval
  src/dao/graph.ts
Labels: enhancement

#218 feat: add entType property to graph nodes for better categorization
  src/dao/graph.ts
Labels: enhancement
